version: "3"

services:
  api:
    container_name: nestjs
    restart: always
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ../src/:/app/src/
    #command: npm run start:dev